name: testing cloudfiles
on:
  workflow_dispatch:

jobs:
  cloudfiles_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install CloudFiles
        run: |
          pip install cloud-files
          mkdir -p ~/.cloudvolume/secrets/
      - name: Look for home directory
        run: |
          echo ~
      - name: Configure S3 secrets
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "aws-secret.json"
          json: ${{ secrets.AWS_SERVICE_ACCOUNT_CREDENTIALS }}
          dir: "/home/runner/.cloudvolume/secrets/"
      - name: List bucket
        run: |
          cloudfiles ls s3://cmip6-pds/
