name: testing mc
on:
  workflow_dispatch:

jobs:
  cloudfiles_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install CloudFiles
        run: |
          pip install cloud-files
      - name: Configure S3 secrets
        env:
          AWS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.AWS_SERVICE_ACCOUNT_CREDENTIALS }}
        run: |
          mkdir -p ~/.cloudvolume/secrets/
          echo "$AWS_SERVICE_ACCOUNT_CREDENTIALS" > ~/.cloudvolume/secrets/aws-secret.json
      - name: List bucket
        run: |
          cloudfiles ls s3://cmip6-pds/
